// catalogoMicroacoesAgenda.ts
// Catálogo dos 06 Domínios Táticos de Tempo do Eixo 06 — Agenda, Capacidade & Tempo.
// Decompõe a rotina do consultório em microações fundamentais em Linguagem Simples.

export type ExecutanteMicroAcao = 'expert' | 'equipe' | 'compartilhado';

export interface MicroAcaoAgenda {
  id: string;
  dominioId: 'tecnico' | 'comercial' | 'gestao' | 'marketing' | 'financeiro' | 'autocuidado';
  titulo: string;
  descricao: string;
  frequenciaPadrao: 'diario' | 'semanal' | 'quinzenal' | 'mensal';
  ocorrenciasPorSemanaPadrao: number;
  duracaoMinutosPadrao: number;
  eixoOrigem?: string; // Ex: 'Eixo 01', 'Eixo 04', 'Eixo 05'
  podeSerDelegado: boolean;
  executanteDefault: ExecutanteMicroAcao;
  papelEquipeRecomendado?: string; // Ex: 'Estagiário de Nutrição', 'Secretária', 'Nutri Assistente'
}

export interface DominioTaticoTempo {
  id: 'tecnico' | 'comercial' | 'gestao' | 'marketing' | 'financeiro' | 'autocuidado';
  titulo: string;
  icone: string;
  corHex: string;
  descricao: string;
  microAcoes: MicroAcaoAgenda[];
}

export const DOMINIOS_TATICOS_AGENDA: DominioTaticoTempo[] = [
  {
    id: 'tecnico',
    titulo: 'Atendimento & Cuidados com o Paciente',
    icone: '🩺',
    corHex: '#10b981', // emerald
    descricao: 'Consultas presenciais e online, escuta ativa, elaboração de dietas e acompanhamentos.',
    microAcoes: [
      {
        id: 'tec_consultas_presenciais',
        dominioId: 'tecnico',
        titulo: 'Consultas presenciais individuais',
        descricao: 'Atendimento olho no olho e acolhimento presencial em consultório.',
        frequenciaPadrao: 'semanal',
        ocorrenciasPorSemanaPadrao: 10,
        duracaoMinutosPadrao: 60,
        eixoOrigem: 'Eixo 01 / Eixo 04',
        podeSerDelegado: false,
        executanteDefault: 'expert',
      },
      {
        id: 'tec_teleconsultas',
        dominioId: 'tecnico',
        titulo: 'Teleconsultas / Atendimentos online',
        descricao: 'Atendimentos por videoconferência com pacientes de qualquer lugar.',
        frequenciaPadrao: 'semanal',
        ocorrenciasPorSemanaPadrao: 5,
        duracaoMinutosPadrao: 50,
        eixoOrigem: 'Eixo 04',
        podeSerDelegado: false,
        executanteDefault: 'expert',
      },
      {
        id: 'tec_anamnese_escuta',
        dominioId: 'tecnico',
        titulo: 'Escuta ativa e conversa comportamental',
        descricao: 'Tempo em consulta dedicado a ouvir hábitos, rotina e histórico de vida.',
        frequenciaPadrao: 'semanal',
        ocorrenciasPorSemanaPadrao: 8,
        duracaoMinutosPadrao: 20,
        eixoOrigem: 'Eixo 01',
        podeSerDelegado: false,
        executanteDefault: 'expert',
      },
      {
        id: 'tec_avaliacao_fisica',
        dominioId: 'tecnico',
        titulo: 'Avaliação física presencial (antropometria e bioimpedância)',
        descricao: 'Medição de peso, dobras cutâneas e bioimpedância.',
        frequenciaPadrao: 'semanal',
        ocorrenciasPorSemanaPadrao: 8,
        duracaoMinutosPadrao: 15,
        podeSerDelegado: true,
        executanteDefault: 'equipe',
        papelEquipeRecomendado: 'Estagiário de Nutrição',
      },
      {
        id: 'tec_montagem_dietas',
        dominioId: 'tecnico',
        titulo: 'Elaboração inicial de cardápios e cálculo de macros',
        descricao: 'Montagem inicial das dietas seguindo a metodologia da clínica.',
        frequenciaPadrao: 'semanal',
        ocorrenciasPorSemanaPadrao: 10,
        duracaoMinutosPadrao: 45,
        eixoOrigem: 'Eixo 01 / Eixo 05',
        podeSerDelegado: true,
        executanteDefault: 'equipe',
        papelEquipeRecomendado: 'Nutri Assistente / Estagiário',
      },
      {
        id: 'tec_pente_fino',
        dominioId: 'tecnico',
        titulo: 'Auditoria de qualidade e revisão final de dietas (Pente-fino)',
        descricao: 'Aprovação final do cardápio elaborado pelo time antes do envio ao paciente.',
        frequenciaPadrao: 'semanal',
        ocorrenciasPorSemanaPadrao: 10,
        duracaoMinutosPadrao: 10,
        podeSerDelegado: false,
        executanteDefault: 'expert',
      },
      {
        id: 'tec_suporte_whatsapp',
        dominioId: 'tecnico',
        titulo: 'Suporte diário no WhatsApp para dúvidas rápidas',
        descricao: 'Respostas a trocas urgentes de alimentos e dúvidas do aplicativo.',
        frequenciaPadrao: 'diario',
        ocorrenciasPorSemanaPadrao: 5,
        duracaoMinutosPadrao: 45,
        eixoOrigem: 'Eixo 05',
        podeSerDelegado: true,
        executanteDefault: 'equipe',
        papelEquipeRecomendado: 'Nutrianjo / Suporte Técnico',
      },
      {
        id: 'tec_ritos_checkin',
        dominioId: 'tecnico',
        titulo: 'Triagem e acompanhamento de check-ins quinzenais',
        descricao: 'Leitura das respostas de evolução e separação dos casos que exigem ajuste.',
        frequenciaPadrao: 'semanal',
        ocorrenciasPorSemanaPadrao: 12,
        duracaoMinutosPadrao: 15,
        eixoOrigem: 'Eixo 05',
        podeSerDelegado: true,
        executanteDefault: 'compartilhado',
        papelEquipeRecomendado: 'Estagiário (Triagem) + Expert (Direcionamento)',
      },
      {
        id: 'tec_onboarding',
        dominioId: 'tecnico',
        titulo: 'Boas-vindas e liberação do aplicativo (Onboarding)',
        descricao: 'Mensagem inicial, envio de questionários e cadastro no app de dieta.',
        frequenciaPadrao: 'semanal',
        ocorrenciasPorSemanaPadrao: 3,
        duracaoMinutosPadrao: 20,
        eixoOrigem: 'Eixo 05',
        podeSerDelegado: true,
        executanteDefault: 'equipe',
        papelEquipeRecomendado: 'Secretária / Assistente',
      },
    ],
  },
  {
    id: 'comercial',
    titulo: 'Vendas & Atração de Pacientes (Gestão de Leads)',
    icone: '🎯',
    corHex: '#6366f1', // indigo
    descricao: 'Social selling no Direct, chamadas comerciais, follow-up e renovação de planos.',
    microAcoes: [
      {
        id: 'com_social_selling',
        dominioId: 'comercial',
        titulo: 'Conversas diárias no Instagram (Direct e enquetes)',
        descricao: 'Atendimento a mensagens recebidas de pessoas interessadas no seu trabalho.',
        frequenciaPadrao: 'diario',
        ocorrenciasPorSemanaPadrao: 5,
        duracaoMinutosPadrao: 30,
        eixoOrigem: 'Eixo 02',
        podeSerDelegado: true,
        executanteDefault: 'compartilhado',
        papelEquipeRecomendado: 'Assistente Comercial / SDR',
      },
      {
        id: 'com_calls_vendas',
        dominioId: 'comercial',
        titulo: 'Conversas de vendas por chamada (Calls de 15 minutos)',
        descricao: 'Chamadas curtas para apresentar os programas de acompanhamento.',
        frequenciaPadrao: 'semanal',
        ocorrenciasPorSemanaPadrao: 6,
        duracaoMinutosPadrao: 20,
        eixoOrigem: 'Eixo 03',
        podeSerDelegado: true,
        executanteDefault: 'expert',
      },
      {
        id: 'com_followup_crm',
        dominioId: 'comercial',
        titulo: 'Acompanhamento de interessados (Follow-up)',
        descricao: 'Recontato estratégico com quem pediu informações e não fechou na hora.',
        frequenciaPadrao: 'semanal',
        ocorrenciasPorSemanaPadrao: 3,
        duracaoMinutosPadrao: 30,
        eixoOrigem: 'Eixo 03',
        podeSerDelegado: true,
        executanteDefault: 'equipe',
        papelEquipeRecomendado: 'Secretária Comercial',
      },
      {
        id: 'com_ritos_renovacao',
        dominioId: 'comercial',
        titulo: 'Conversas para renovação de planos',
        descricao: 'Rito de renovação de contrato conduzido no final do plano atual.',
        frequenciaPadrao: 'semanal',
        ocorrenciasPorSemanaPadrao: 3,
        duracaoMinutosPadrao: 25,
        eixoOrigem: 'Eixo 03 / Eixo 04',
        podeSerDelegado: true,
        executanteDefault: 'compartilhado',
        papelEquipeRecomendado: 'Secretária (Aviso) + Expert (Proposta)',
      },
    ],
  },
  {
    id: 'gestao',
    titulo: 'Gestão da Equipe & Ritos de Liderança',
    icone: '👥',
    corHex: '#f59e0b', // amber
    descricao: 'Reuniões de alinhamento, auditoria 5-5-5-5, estudo de casos e treinamentos.',
    microAcoes: [
      {
        id: 'ges_daily_meeting',
        dominioId: 'gestao',
        titulo: 'Reunião diária rápida de alinhamento (Daily - 15 min)',
        descricao: 'Encontro rápido de manhã com o time para alinhar prioridades do dia.',
        frequenciaPadrao: 'diario',
        ocorrenciasPorSemanaPadrao: 5,
        duracaoMinutosPadrao: 15,
        podeSerDelegado: false,
        executanteDefault: 'expert',
      },
      {
        id: 'ges_weekly_meeting',
        dominioId: 'gestao',
        titulo: 'Reunião semanal de gestão (Segunda-feira)',
        descricao: 'Revisão dos números de faturamento, novos pacientes e metas.',
        frequenciaPadrao: 'semanal',
        ocorrenciasPorSemanaPadrao: 1,
        duracaoMinutosPadrao: 60,
        podeSerDelegado: false,
        executanteDefault: 'expert',
      },
      {
        id: 'ges_auditoria_5555',
        dominioId: 'gestao',
        titulo: 'Auditoria de qualidade aleatória (Método 5-5-5-5)',
        descricao: 'Amostragem rápida de 5 conversas, 5 dietas e 5 atendimentos da equipe.',
        frequenciaPadrao: 'semanal',
        ocorrenciasPorSemanaPadrao: 3,
        duracaoMinutosPadrao: 30,
        podeSerDelegado: false,
        executanteDefault: 'expert',
      },
      {
        id: 'ges_casos_clinicos',
        dominioId: 'gestao',
        titulo: 'Discussão de casos clínicos difíceis com o time',
        descricao: 'Orientação técnica para a equipe sobre pacientes de alta complexidade.',
        frequenciaPadrao: 'semanal',
        ocorrenciasPorSemanaPadrao: 1,
        duracaoMinutosPadrao: 45,
        podeSerDelegado: false,
        executanteDefault: 'expert',
      },
    ],
  },
  {
    id: 'marketing',
    titulo: 'Marketing, Conteúdo & Comunidade de Pacientes',
    icone: '📢',
    corHex: '#ec4899', // pink
    descricao: 'Gravação de vídeos em lote, Stories, comunidade de pacientes e eventos.',
    microAcoes: [
      {
        id: 'mkt_gravacao_lote',
        dominioId: 'marketing',
        titulo: 'Gravação em bloco (Batching) de conteúdo',
        descricao: 'Reserva de 1h a 2h na semana para gravar vários vídeos de uma vez só.',
        frequenciaPadrao: 'semanal',
        ocorrenciasPorSemanaPadrao: 1,
        duracaoMinutosPadrao: 90,
        podeSerDelegado: false,
        executanteDefault: 'expert',
      },
      {
        id: 'mkt_stories_diarios',
        dominioId: 'marketing',
        titulo: 'Stories diários e rotina autoral',
        descricao: 'Postagem da sua rotina, lifestyle e alimentação intencional.',
        frequenciaPadrao: 'diario',
        ocorrenciasPorSemanaPadrao: 5,
        duracaoMinutosPadrao: 20,
        podeSerDelegado: false,
        executanteDefault: 'expert',
      },
      {
        id: 'mkt_moderacao_comunidade',
        dominioId: 'marketing',
        titulo: 'Acompanhamento do grupo de pacientes no WhatsApp',
        descricao: 'Envio de incentivos diários e interação na comunidade.',
        frequenciaPadrao: 'diario',
        ocorrenciasPorSemanaPadrao: 5,
        duracaoMinutosPadrao: 15,
        podeSerDelegado: true,
        executanteDefault: 'compartilhado',
        papelEquipeRecomendado: 'Nutrianjo / Suporte de Comunidade',
      },
    ],
  },
  {
    id: 'financeiro',
    titulo: 'Administração, Finanças & Softwares',
    icone: '💰',
    corHex: '#3b82f6', // blue
    descricao: 'Controle de caixa, faturamento, notas fiscais e organização dos sistemas.',
    microAcoes: [
      {
        id: 'fin_controle_caixa',
        dominioId: 'financeiro',
        titulo: 'Conferência de entradas e controle de caixa',
        descricao: 'Acompanhamento do faturamento e custos do consultório.',
        frequenciaPadrao: 'semanal',
        ocorrenciasPorSemanaPadrao: 1,
        duracaoMinutosPadrao: 45,
        eixoOrigem: 'Eixo 08',
        podeSerDelegado: true,
        executanteDefault: 'equipe',
        papelEquipeRecomendado: 'Secretária / Contador',
      },
      {
        id: 'fin_burocracia_notas',
        dominioId: 'financeiro',
        titulo: 'Emissão de notas fiscais, boletos e burocracia',
        descricao: 'Envio de recibos, notas fiscais e acerto de contas.',
        frequenciaPadrao: 'semanal',
        ocorrenciasPorSemanaPadrao: 1,
        duracaoMinutosPadrao: 40,
        eixoOrigem: 'Eixo 08',
        podeSerDelegado: true,
        executanteDefault: 'equipe',
        papelEquipeRecomendado: 'Secretária / Assistente Financeiro',
      },
    ],
  },
  {
    id: 'autocuidado',
    titulo: 'Estudo, Saúde & Autocuidado do Nutricionista',
    icone: '🧠',
    corHex: '#8b5cf6', // purple
    descricao: 'Estudo diário de artigos, treinos, saúde física e momentos de descanso.',
    microAcoes: [
      {
        id: 'aut_estudo_focado',
        dominioId: 'autocuidado',
        titulo: 'Bloco de estudo diário (artigos científicos e cursos)',
        descricao: 'Leitura técnica de novos artigos e capacitação contínua.',
        frequenciaPadrao: 'diario',
        ocorrenciasPorSemanaPadrao: 5,
        duracaoMinutosPadrao: 45,
        podeSerDelegado: false,
        executanteDefault: 'expert',
      },
      {
        id: 'aut_autocuidado_treino',
        dominioId: 'autocuidado',
        titulo: 'Horários sagrados de treino, saúde e autocuidado',
        descricao: 'Bloqueio fixo na agenda para atividade física, sono e hábitos saudáveis.',
        frequenciaPadrao: 'diario',
        ocorrenciasPorSemanaPadrao: 5,
        duracaoMinutosPadrao: 60,
        podeSerDelegado: false,
        executanteDefault: 'expert',
      },
    ],
  },
];
